[project]
name = "finbotics"
version = "0.1.0"
description = "finbotics using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.102.0,<1.0.0"
]

[project.scripts]
finbotics = "finbotics.main:run"
run_crew = "finbotics.main:run"
train = "finbotics.main:train"
replay = "finbotics.main:replay"
test = "finbotics.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
